name: terraform-cd

on:
  workflow_call:
    inputs:
      terraform-version:
        required: true
        type: string
      terraform-directory:
        required: true
        type: string
      terraform-var-file:
        required: true
        type: string
      terraform-backend-config:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      aws-role:
        required: true
        type: string  

jobs:
  terraform-cd:
    name: terraform-cd
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.terraform-directory }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Terraform Init
      id: init
      run: terraform init -backend-config ${{ inputs.terraform-backend-config }} -upgrade

    - name: Terraform Apply
      id: apply
      run: terraform apply -var-file ${{ inputs.terraform-var-file }} -auto-approve -input=false