name: terraform-docs

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      output-file:
        required: true
        type: string

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ${{ inputs.working-dir }}
        output-file: ${{ inputs.output-file }}
        output-method: inject
        git-push: "true"